---
name: "Go - Test"
description: |
  This action runs `go test` over the working tree and then verifies
  that there are no differences from running the tool.
inputs:
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
  timeout:
    description: "Maximum duration before the test suite times out."
    default: "20m"
    required: false
  tags:
    description: "Build tags passed to `go test`"
    default: ""
    required: false
  race:
    description: "If false, race detection is disabled in testing"
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Run Go Build"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: "go test --race '${{ inputs.race }}' --failfast --tags '${{ inputs.tags }}' -timeout '${{ inputs.timeout }}' ./..."
