---
name: "Buf - Format"
description: |
  This actions runs `buf format` in the working tree and then verifies that
  there are no differences from running the tool.
inputs:
  version:
    description: "Buf version used to generate"
    default: "1.18.0"
    required: false
runs:
  using: "composite"
  steps:
    - uses: "bufbuild/buf-setup-action@v1"
      with:
        version: "${{ inputs.version }}"
    - name: "Format Protos"
      shell: "bash"
      run: "buf format --diff --exit-code"
