---
name: "YAML - Lint"
description: |
  This action runs `yamllint` over the working tree and then verifies
  that there are no differences from running the tool.
inputs:
  config_file:
    description: "Config file name under working directory"
    default: ".yamllint"
    required: false
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
runs:
  using: "composite"
  steps:
    - uses: "ibiqlik/action-yamllint@v3"
      with:
        file_or_dir: "${{ inputs.working_directory }}"
        config_file: "${{ inputs.working_directory }}/${{ inputs.config_file }}"
      env:
        TMPDIR: "${{ runner.temp }}"
