---
name: "Setup Go Jsonnet"
description: "Download and install Go Jsonnet"
inputs:
  version:
    description: "Version of Jsonnet to install. Default: `v0.21.0`"
    required: false
    default: "v0.21.0"
runs:
  using: "composite"
  steps:
    - uses: "zendesk/setup-jsonnet@v16"
      with:
        version: "${{ inputs.version }}"
