---
name: "Docker - Build"
description: "This action runs `docker build` over the working tree."
inputs:
  push:
    description: "Push is a shorthand for --output=type=registry"
    default: "false"
    required: false
  tags:
    description: "List of tags"
    default: "latest"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    default: "."
    required: false
  file:
    description: "Path to the Dockerfile"
    default: "Dockerfile"
    required: false

runs:
  using: "composite"
  steps:
    - uses: "docker/setup-qemu-action@v1"
    - uses: "docker/setup-buildx-action@v1"
      with:
        driver-opts: "image=moby/buildkit:master"
    - uses: "docker/build-push-action@v2"
      with:
        context: "${{ inputs.context }}"
        file: "${{ inputs.file }}"
        push: "${{ inputs.push == 'true' }}"
        tags: "${{ inputs.tags }}"
