name: "Semantic Version Update"
description: "Updates the semantic version of a package"
inputs:
  sourcefile-path:
    description: "The path of the source file containing the version to be changed"
    required: true
    default: ""
  version-regex:
    description: "Regular expression for finding the existing version from the source file and replacing it"
    required: true
    default: ""
  version-change:
    description: "The portion of the version to bump"
    required: false
    default: "minor" # One of: "major", "minor", "package", or a particular version (to set it explicitly)
runs:
  using: "node16"
  main: "index.js"
