---
name: "Setup Mage"
description: "Download and install Mage"
inputs:
  version:
    description: "Version of Mage to install"
    default: "v1.15.0"
    required: false
runs:
  using: "composite"
  steps:
    - uses: "magefile/mage-action@6f50bbb8ea47d56e62dee92392788acbc8192d0b" # v3.1.0
      with:
        version: "${{ inputs.version }}"
        install-only: true
