---
name: "Go - Build"
description: |
  This action runs `go build` over the cmd directory.
inputs:
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
  ldflags:
    description: "Optional ldflags to pass to go build (e.g., '-X main.version=1.0.0')"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: "Run Go Build"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: |
        if [ -n "${{ inputs.ldflags }}" ]; then
          go build -ldflags="${{ inputs.ldflags }}" ./cmd/...
        else
          go build ./cmd/...
        fi
