---
name: "Go - Linting"
description: "This action runs golangci-lint over the working tree."
inputs:
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
runs:
  using: "composite"
  steps:
    - uses: "golangci/golangci-lint-action@v3"
      with:
        working-directory: "${{ inputs.working_directory }}"
        version: "v1.48"
        skip-pkg-cache: true
        skip-build-cache: false
