---
name: "Go - Linting"
description: "This action runs golangci-lint over the working tree."
inputs:
  args:
    description: "golangci-lint command line arguments"
    default: ""
    required: false
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
runs:
  using: "composite"
  steps:
    - uses: "golangci/golangci-lint-action@v8"
      with:
        working-directory: "${{ inputs.working_directory }}"
        args: "${{ inputs.args }}"
        version: "v2.2.2"
