---
name: "CLA - Check"
description: "This action determines if commit authors have signed a CLA."
inputs:
  github_token:
    description: "explicit passing of GITHUB_TOKEN secret"
    required: true
  cla_assistant_token:
    description: "explicit passing of CLA_ASSISTANT_ACCESS_TOKEN secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup environment"
      shell: "bash"
      run: |
        # Persist the env into future commands.
        GITHUB_TOKEN="${{ inputs.github_token }}"
        echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
        CLA_TOKEN="${{ inputs.cla_assistant_token}}"
        echo "PERSONAL_ACCESS_TOKEN=${CLA_TOKEN}" >> $GITHUB_ENV
    - name: "CLA Check"
      if: "(github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'"
      uses: "cla-assistant/github-action@v2.1.3-beta"
      with:
        remote-organization-name: "authzed"
        remote-repository-name: "cla"
        path-to-signatures: "v1/signatures.json"
        path-to-document: "https://github.com/authzed/cla/blob/main/v1/icla.md"
        branch: "main"
        allowlist: "authzedbot,dependabot[bot],renovate-bot"
