---
name: "Docker - Login"
description: "This action runs `docker login` for various registries."
runs:
  using: "composite"
  steps:
    - uses: "docker/login-action@v1"
      with:
        registry: "quay.io"
        username: "${{ secrets.QUAYIO_USER }}"
        password: "${{ secrets.QUAYIO_PASSWORD }}"
    - uses: "docker/login-action@v1"
      with:
        registry: "ghcr.io"
        username: "${{ github.actor }}"
        password: "${{ secrets.GHCR_TOKEN }}"
    - uses: "docker/login-action@v1"
      with:
        username: "${{ secrets.DOCKERHUB_USER }}"
        password: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
