---
name: "Go - Licenses Check"
description: |
  This action runs `go-licenses check` over the working tree to verify that
  there are no disallowed licenses used by imported packages.
  See: https://github.com/google/go-licenses?tab=readme-ov-file#checking-for-forbidden-licenses
inputs:
  version:
    description: "The version of go-licenses used if it is not already installed."
    default: "latest"
    required: false
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
  ignore:
    description: "The packages to ignore, if any"
    default: "none"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install Go Licenses"
      id: "golicenses-install"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: |
        if which go-licenses > /dev/null; then
          echo "found existing go-licenses installed"
        else
          go install github.com/google/go-licenses@${{ inputs.version }}
        fi
    - name: "Run Go Licenses Check"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: "go-licenses check --include_tests --ignore ${{ inputs.ignore }} ./..."
