---
name: "Go - Modules Tidy"
description: |
  This action runs `go mod tidy` over the working tree and then verifies
  that there are no differences from running the tool.
inputs:
  working_directory:
    description: "The directory with the root of the project"
    default: "."
    required: false
runs:
  using: "composite"
  steps:
    - name: "Run Go Mod Tidy"
      shell: "bash"
      working-directory: "${{ inputs.working_directory }}"
      run: "go mod tidy"
    - name: "Verify Go Mod Tidy"
      uses: "chainguard-dev/actions/nodiff@main"
      with:
        fixup-command: "go mod tidy"
